"""Add is_available, and stock_quantity to Products and ProductParts

Revision ID: 9f1462128931
Revises: 8880b244afb7
Create Date: 2025-01-25 17:13:31.911308

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f1462128931"
down_revision: Union[str, None] = "8880b244afb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "part_variants",
        sa.Column(
            "is_available",
            sa.Boolean(),
            nullable=False,
            server_default="1",
        ),
    )
    op.add_column(
        "part_variants",
        sa.Column(
            "stock_quantity",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "is_available",
            sa.Boolean(),
            nullable=False,
            server_default="1",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "stock_quantity",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "stock_quantity")
    op.drop_column("products", "is_available")
    op.drop_column("part_variants", "stock_quantity")
    op.drop_column("part_variants", "is_available")
    # ### end Alembic commands ###
