"""Add variant dependencies table

Revision ID: d4dd83f66239
Revises: 7047d7cff50c
Create Date: 2025-01-25 22:14:43.065575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4dd83f66239"
down_revision: Union[str, None] = "7047d7cff50c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "variant_dependencies",
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("restrictions", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["part_variants.id"],
        ),
        sa.PrimaryKeyConstraint("variant_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("variant_dependencies")
    # ### end Alembic commands ###
